### ISSUE TITLE
help for: using the four external views from two stereo cameras as paired data[DROID]

### ISSUE THREAD

**Issue by zhou-pig** [s-tian/VISTA#1]
Thank you for the good work! The paper mentioned four external views, but I found that DROID only has two external cameras and one wrist camera. What do the four external views refer to? How did you get it?

**Comment by s-tian** [comment]
Hi, thanks for your interest in our work, and apologies for the late response. The four external views are derived from the two stereo external cameras. Each stereo camera provides two views: a left and a right view, resulting in four views in total.
