### ISSUE TITLE
Environment not implimented

### ISSUE THREAD

**Issue by Ramseyous0109** [s-tian/VISTA#3]
Hi, thanks for this excellent work. I encounter a problem when converting source datasets to potentially augmented datasets for some of the demos.

Running command: 

```bash
python dataset_states_to_obs_zeronvs.py --dataset /path/to/VISTA/data/small_perturb/threading/threading_d0_200.hdf5 --output_name rand
om_cam_zeronvs.hdf5  --done_mode 2 --randomize_cam_range small_perturb --camera_names agentview robot0_eye_in_hand --camera_height 84 --camera_width 84 --compress --randomize_cam --parse-iters 1 --camera_ran
domization_type zeronvs_lpips_guard --n 5 --start-idx 0
```

Error Message: 

```bash
Traceback (most recent call last):
  File "/home/lxy/work/vista/VISTA/robomimic/robomimic/scripts/dataset_states_to_obs_zeronvs.py", line 600, in <module>
    dataset_states_to_obs(args)
  File "/home/lxy/work/vista/VISTA/robomimic/robomimic/scripts/dataset_states_to_obs_zeronvs.py", line 276, in dataset_states_to_obs
    env = EnvUtils.create_env_for_data_processing(
  File "/home/lxy/work/vista/VISTA/robomimic/robomimic/utils/env_utils.py", line 300, in create_env_for_data_processing
    env = env_class.create_for_data_processing(
  File "/home/lxy/work/vista/VISTA/robomimic/robomimic/envs/env_robosuite.py", line 483, in create_for_data_processing
    return cls(
  File "/home/lxy/work/vista/VISTA/robomimic/robomimic/envs/env_robosuite.py", line 100, in __init__
    self.env = robosuite.make(self._env_name, **kwargs)
  File "/home/lxy/work/vista/VISTA/robosuite/robosuite/environments/base.py", line 35, in make
    raise Exception(
Exception: Environment Threading_D0 not found. Make sure it is a registered environment among: Lift, Stack, NutAssembly, NutAssemblySingle, NutAssemblySquare, NutAssemblyRound, PickPlace, PickPlaceSingle, PickPlaceMilk, PickPlaceBread, PickPlaceCereal, PickPlaceCan, Door, Wipe, ToolHang, TwoArmLift, TwoArmPegInHole, TwoArmHandover, TwoArmTransport
```

It seems some of the environments used in the experiments in robosuite is not specified.

Looking forward to your reply.

**Comment by s-tian** [comment]
Hi, thanks for your question and your interest in our work. 

I think this error is because the mimicgen_environments package is not installed. Could you please install that as well as robosuite_task_zoo if they are not already installed?

```
git clone https://github.com/NVlabs/mimicgen_environments
cd mimicgen_environments
pip install -e .
cd ..
git clone https://github.com/ARISE-Initiative/robosuite-task-zoo
git checkout 74eab7f88214c21ca1ae8617c2b2f8d19718a9ed
cd robosuite_task_zoo
pip install -e .
```

Please let me know if this helps!
Stephen

**Comment by s-tian** [comment]
Hi,

Thanks for your reply! Upon further inspection, I think this might be because `mimicgen_environments` has recently renamed their package to be called `mimicgen`. Can you try replacing `import mimicgen_envs` in L65 of https://github.com/s-tian/VISTA/blob/main/robomimic/robomimic/scripts/dataset_states_to_obs_zeronvs.py#L65 with `import mimicgen`? I think this will resolve the problem. If it does, I'll update the repo to fix this.

Thanks,
Stephen

**Comment by Ramseyous0109** [comment]
> Hi,
> 
> Thanks for your reply! Upon further inspection, I think this might be because `mimicgen_environments` has recently renamed their package to be called `mimicgen`. Can you try replacing `import mimicgen_envs` in L65 of https://github.com/s-tian/VISTA/blob/main/robomimic/robomimic/scripts/dataset_states_to_obs_zeronvs.py#L65 with `import mimicgen`? I think this will resolve the problem. If it does, I'll update the repo to fix this.
> 
> Thanks, Stephen

Hi Stephen,

This works for me. The problem is solved by replacing the imported package. Thanks again for your patience !

**Comment by s-tian** [comment]
Great!
